services:
  ollama-server:
    image: ollama-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama-data:/root/.ollama  # Persistent storage for models
    ports:
      - "8080:8080"  # FastAPI API management
      - "11434:11434"  # Ollama serving port
    runtime: nvidia  # Ensure NVIDIA runtime is used
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    container_name: ollama-server

volumes:
  ollama-data:
    driver: local
